### ISSUE TITLE
Ruby Capstone Task Assignment

### ISSUE THREAD

**Issue by gisachris** [gisachris/ruby-capstone-project#5]
**link to kanban board** [here](https://github.com/gisachris/ruby-capstone-project/projects/1)
## Hello there, CR 👋 
**Our team consists of three people 🧑‍🤝‍🧑 :**
- @VaheStepanyan100 was assigned 📚 (`books` class)
- @Enoisong was assigned 🎹 (`music` class)
- @gisachris  was assigned 🎲 (`game` class)

**Comment by Gambit142** [comment]
Hi @VaheStepanyan100 @gisachris @Enoisong 👋, 

Good job so far!

## Highlights
- Created Kanban board from the template given ✔️ 
- All cards are assigned to a team member ✔️ 
- All cards are assigned in a fair way ✔️ 

You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️

- [ ] The tasks are lumped up into one card per team member. The essence of the Kanban board is to break tasks into bits for easy workflow management. Breaking tasks into smaller bits on a Kanban board helps improve task visibility, enhances collaboration, and enables a more granular and manageable workflow for efficient task tracking and completion. 👍 

Kindly represent each group and individual requirement with a card on the Kanban board and assign them to Team members accordingly in a fair manner. Also, please ensure that they have descriptive titles. 💻 🖱️ 

#### Hint: Meet the requirements in this screenshot pasted below:

![image](https://github.com/gisachris/ruby-capstone-project/assets/77106962/812489ce-6062-4c47-9e87-712eeb0cba67)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

You can also consider the following:

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by prolajumokeoni** [comment]
Hi @Team

Your board setup is complete! 
Congratulations! 🎉 
## Highlights
 - Good setup   💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
